server:
  port: ${random.int(5000,5100)}
  servlet:
    context-path: /coe
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pruebas
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update